name: PR Build

on:
    pull_request_target:
        branches: [master]
        types: [opened, synchronize, reopened]

permissions:
    contents: read
    pull-requests: write
    checks: write
    statuses: write

env:
    PLUGIN_ID: yearly-glance

jobs:
    # 安全检查作业 - 验证 PR 来源
    security-check:
        runs-on: ubuntu-latest
        outputs:
            is-safe: ${{ steps.check.outputs.is-safe }}
        steps:
            - name: Check PR safety
              id: check
              run: |
                  # 检查是否来自同一仓库或具有安全标签
                  if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]] || \
                     [[ "${{ contains(github.event.pull_request.labels.*.name, 'safe-to-build') }}" == "true" ]]; then
                    echo "is-safe=true" >> $GITHUB_OUTPUT
                  else
                    echo "is-safe=false" >> $GITHUB_OUTPUT
                  fi

    build:
        runs-on: ubuntu-latest
        needs: security-check
        if: needs.security-check.outputs.is-safe == 'true'
        steps:
            - name: Checkout PR code
              uses: actions/checkout@v4
              with:
                  # 重要：检出 PR 的代码而不是目标分支
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
                  cache: "npm"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build plugin
              run: yarn build

            - name: Prepare artifacts
              run: |
                  mkdir -p build-artifacts
                  cp main.js manifest.json styles.css build-artifacts/
                  cd build-artifacts
                  zip -r "${{ env.PLUGIN_ID }}-pr-${{ github.event.number }}.zip" .

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: plugin-pr-${{ github.event.number }}
                  path: build-artifacts/
                  retention-days: 7

            - name: Comment on PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const prNumber = context.payload.pull_request.number;
                      const shortSha = context.payload.pull_request.head.sha.substring(0, 7);
                      const runId = context.runId;

                      const commentBody = `## 🔧 PR 构建完成

                      **构建信息：**
                      - PR: #${prNumber}
                      - Commit: ${shortSha}
                      - 构建时间: ${new Date().toISOString()}

                      **下载链接：**
                      [下载插件构建产物](https://github.com/${{ github.repository }}/actions/runs/${runId})

                      **安装说明：**
                      1. 点击上方链接下载构建产物
                      2. 解压 zip 文件
                      3. 将解压后的文件夹复制到 Obsidian 插件目录：\`<vault>/.obsidian/plugins/${{ env.PLUGIN_ID }}/\`
                      4. 在 Obsidian 设置中启用插件

                      > ⚠️ 这是测试构建，仅用于预览和测试目的。`;

                      // 查找现有的构建评论
                      const comments = await github.rest.issues.listComments({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: prNumber
                      });

                      const existingComment = comments.data.find(comment => 
                        comment.user.login === 'github-actions[bot]' && 
                        comment.body.includes('🔧 PR 构建完成')
                      );

                      if (existingComment) {
                        await github.rest.issues.updateComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          comment_id: existingComment.id,
                          body: commentBody
                        });
                      } else {
                        await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: prNumber,
                          body: commentBody
                        });
                      }

    build-status:
        runs-on: ubuntu-latest
        needs: [security-check, build]
        if: always() && needs.security-check.outputs.is-safe == 'true'
        steps:
            - name: Set commit status
              uses: actions/github-script@v7
              with:
                  script: |
                      const state = '${{ needs.build.result }}' === 'success' ? 'success' : 'failure';
                      const description = state === 'success' ? 'PR 构建成功' : 'PR 构建失败';

                      await github.rest.repos.createCommitStatus({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        sha: '${{ github.event.pull_request.head.sha }}',
                        state: state,
                        description: description,
                        context: 'PR Build',
                        target_url: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
                      });
